/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include<sys/wait.h>
#include<utime.h>
#ifndef _DEXOPT
#define _DEXOPT
#ifdef __cplusplus

extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_openatlas_dexopt_InitExecutor_dexopt(JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
